# Generated by Django 3.2.16 on 2022-11-29 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Сюды текст надо для письма')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 21, 31, 34, 651823))),
            ],
        ),
    ]
