# Generated by Django 3.2.16 on 2022-11-22 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 11, 22, 22, 55, 18, 108919))),
            ],
        ),
    ]
