# Generated by Django 3.2.16 on 2022-11-29 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 21, 40, 54, 159551)),
        ),
    ]
