# Generated by Django 3.2.16 on 2022-12-06 15:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 22, 25, 21, 808255)),
        ),
    ]
