# Generated by Django 3.2.16 on 2022-12-07 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_alter_feedback_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 21, 59, 53, 324862)),
        ),
    ]
