# Generated by Django 3.2.16 on 2022-12-08 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_alter_feedback_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обатные связи'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 17, 43, 40, 321617)),
        ),
    ]
