# Generated by Django 3.2.16 on 2022-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='rate',
            field=models.CharField(choices=[('1', 'Ненависть'), ('2', 'Неприязнь'), ('3', 'Нейтрально'), ('4', 'Обожание'), ('5', 'Любовь')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='raiting',
            constraint=models.UniqueConstraint(fields=('user', 'rate'), name='rating_once'),
        ),
    ]
