# Generated by Django 3.2.16 on 2022-12-05 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_item_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0002_auto_20221205_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
    ]
