# Generated by Django 3.2.16 on 2022-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rename_raiting_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')]),
        ),
    ]
