# Generated by Django 3.2.16 on 2022-12-08 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20221208_2344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0005_auto_20221208_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(help_text='Предмет оценки.', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], help_text='Оценка товара.'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='Оценщик товара.', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
