# Generated by Django 3.2.16 on 2022-11-08 14:16

import catalog.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221107_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
    ]
