# Generated by Django 3.2.16 on 2022-11-08 16:38

import catalog.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20221108_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
