# Generated by Django 3.2.16 on 2022-12-08 14:43

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20221207_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Проверка на публикацю.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Вес, должен быть 0 до 32767.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='вес'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Категория. Связь o2m.', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='catalog.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_on_main',
            field=models.BooleanField(default=False, verbose_name='В главной?'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Проверка на публикацю.', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Теги. Связь m2m.', related_name='tags', to='catalog.Tag', verbose_name='тэги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_galery',
            field=models.ForeignKey(blank=True, help_text='Фотографии предмета.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_galery', to='catalog.item', verbose_name='галерея фотографий'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='item_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_main', to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Проверка на публикацю.', verbose_name='опубликовано'),
        ),
    ]
