# Generated by Django 3.2.16 on 2022-11-09 15:58

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_item_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='item',
        ),
        migrations.AddField(
            model_name='photo',
            name='item_galery',
            field=models.ForeignKey(blank=True, help_text='фотографии предмета.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_galery', to='catalog.item', verbose_name='галерея фотографий'),
        ),
        migrations.AddField(
            model_name='photo',
            name='item_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
    ]
