# Generated by Django 3.2.16 on 2022-11-09 16:14

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20221109_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='item_main',
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
    ]
