# Generated by Django 3.2.16 on 2022-11-09 16:16

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20221109_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='item_galery',
        ),
        migrations.AddField(
            model_name='photo',
            name='item',
            field=models.ForeignKey(blank=True, help_text='фотографии предмета.', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='галерея фотографий'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Описание предмета. Должны быть слова "превосходно" или "роскошно".', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
    ]
